### PR TITLE
Intialized blog api

### PR DESCRIPTION
**Pull request by mr-jackpot**
check tests running etc, thanks

### CODE REVIEW

**Review by JordT — CHANGES_REQUESTED** [review]
Can you add a .gitignore file to the blog-api root folder, to ensure we aren't pushing node_modules to the repo? You might need to remove node_moduels from your commit too.

I was unable to start the server as you've not added Express as a dependency in the package.json.

Finally, we should use nodemon so the server live updates as we work :)

**Comment by mr-jackpot** [comment]
> Can you add a .gitignore file to the blog-api root folder, to ensure we aren't pushing node_modules to the repo? You might need to remove node_moduels from your commit too.

Thanks for the review, working on it this afternoon will re-send review ⚙️

**Comment by mr-jackpot** [comment]
Added express in 40b3c72

**Review by JordT — APPROVED** [review]
Changes look good - I've tested and working locally 👾

**Pull request merged**
